name: Python application

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Remove previous heroku builds
      run: |
        heroku plugins:install heroku-builds
        heroku builds:cancel -a ${{secrets.HEROKU_API_NAME}}
        heroku restart -a ${{secrets.HEROKU_API_NAME}}
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: ${{secrets.HEROKU_API_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
